### ISSUE TITLE
localStorage.getItem('A KEY') returns undefined

### ISSUE THREAD

**Issue by r1c4r60** [aihornmac/mobx-localstorage#1]
Function: getItem
Expected: null result for a key that doesn't exist
Actual result: got underfined for a key that doesn't exist

https://html.spec.whatwg.org/multipage/webstorage.html

> The getItem(key) method must return the current value associated with the given key. If the given key does not exist in the list associated with the object then this method must return null.

**Comment by aihornmac** [comment]
@r1c4r60 sorry for the late reply, I didn't receive the notification from GitHub.
`getItem` actually do `JSON.parse`, rather than returning the original string. So since the given key does not exist, I just return undefined, just like a plain object.
Maybe it'd be better stick to the spec. Thanks for your contribution!

**Comment by aihornmac** [comment]
@r1c4r60 [mobx-localstorage@1.1.0](https://www.npmjs.com/package/mobx-localstorage/v/1.1.0) should solve this.
